version: '3.8'

services:
  ## Operations Service ##
  snippet-operations-db:
    image: postgres:15.2
    container_name: snippet_operations_db
    env_file:
      - env/operations/operationsdb.env
    ports:
      - "5432:5432"
    volumes:
      - operations_db_data:/var/lib/postgresql/data
  snippet-operations:
    image: ghcr.io/ingsisahre/snippetoperations-dev:dev
    container_name: snippet-operations
    environment:
      NEW_RELIC_APP_NAME: "Snippet Operations Dev"
    env_file:
      - env/operations/operations.env
    ports:
      - "8081:8081"
    depends_on:
      - snippet-operations-db
      - api
      - redis
  ## Permission Service ##
  snippet-permission-db:
    image: postgres:15.2
    container_name: snippet_permission_db
    env_file:
      - env/permission/permissiondb.env
    ports:
      - "5433:5433"
    volumes:
      - permission_db_data:/var/lib/postgresql/data

  snippet-permission:
    image: ghcr.io/ingsisahre/snippetpermission-dev:dev
    container_name: snippet-permission
    environment:
      NEW_RELIC_APP_NAME: "Snippet Permissions Dev"
    env_file:
      - env/permission/permission.env
    ports:
      - "8082:8082"
    depends_on:
      - snippet-permission-db
  ## Runner Service ##
  snippet-runner:
    image: ghcr.io/ingsisahre/snippetrunner-dev:dev
    container_name: snippet-runner
    environment:
      NEW_RELIC_APP_NAME: "Snippet Runner Dev"
    env_file:
      - env/runner/runner.env
    ports:
      - "8083:8083"

  api:
    container_name: asset-service
    image: "ghcr.io/austral-ingsis/snippet-asset-service:latest"
    ports:
      - "8080:8080"
    environment:
      NEW_RELIC_AGENT_ENABLED: false
    env_file:
      - env/asset.env

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: "azurite"
    hostname: azurite
    restart: always
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    volumes:
      - blob:/workspace

  redis:
    container_name: "snippet-redis"
    image: redis:6-alpine
    ports:
      - "6379:6379"

volumes:
  operations_db_data:
  permission_db_data:
  blob:
    external: false
